### PR TITLE
update to honister's new override style syntax

### PR DESCRIPTION
**Pull request by ejoerns**
Done with conversion script:

  scripts/contrib/convert-overrides.py meta-ptx

Update layer compatibility to honister (only).

### CODE REVIEW

**Comment by jluebbe** [comment]
The branches of gatesgarth and hardknott already support the new syntax, but have not received a release tag yet. Do we want to remove compatibility now only to add it soon again?

**Comment by ejoerns** [comment]
As we do not test master against any poky release, there is no real compatibility promise at all.

For the other updates to the next poky release, I kept in (only) the previous version still (thus gatesgarth would be dropped anyway) but this is also more or less a compromise and similar to what meta-oe does.

Thus yes, we could keep hardknott in, just like for the other updates.

**Comment by ejoerns** [comment]
I've updated layer.conf and commit message accordingly.

**Review by jluebbe — APPROVED** [review]
Looks good.

**Pull request merged**
