### PR TITLE
distro/ptx.conf: update to dunfell (3.1)

### PR DESCRIPTION
**Pull request by Emantor**
Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>

### CODE REVIEW

**Comment by ejoerns** [comment]
@Emantor Thanks for the update!

Note that poky also added

``` diff
 INHERIT += "uninative"
+
+INHERIT += "reproducible_build"
+
+BB_SIGNATURE_HANDLER ?= "OEEquivHash"
+BB_HASHSERVE ??= "auto"
```

when moving the distro config from zeus to dunfell. I'd like to have this reflected in the ptx.conf, too.

**Comment by Emantor** [comment]
Done.

**Comment by Emantor** [comment]
@ejoerns gentle ping.

**Review by ejoerns — APPROVED** [review]
Looks good for me now, thx! :+1:

**Comment by ejoerns** [comment]
I've now pushed the current `master` branch to `dunfell`, too.

**Pull request merged**
