### PR TITLE
Add bootspec support for external device tree's

### PR DESCRIPTION
**Pull request by bith3ad**
The purpose of this PR is to add the support for external (BSP) device tree's.

Those device tree's can be build by a BSP recipes using the Poky devicetree.bbclass.

### CODE REVIEW

**Comment by ejoerns** [comment]
@medude I've updated the original patch to match the rework of #68:
https://github.com/ejoerns/meta-ptx/commit/318a4defeeab819047767c0bd62a771003ce062e

Feel free to check if you agree with those changes (and the fixes in commit messages), then we could update the PR accordingly.

**Comment by medude** [comment]
@ejoerns Thanks for your update. Unfortunately it's not that simple since the external class can build .dtbo as well which will added to ext_dtbs now. I will pick your commit and add the handling for the dtbo and update the PR. Thanks for your work :)

**Comment by ejoerns** [comment]
@medude Ah, got it. It lacks something like

``` python
dtbs=[x for x in dtbs if x.endswith('.dtb')]
```

**Comment by jluebbe** [comment]
How will overlays be handled? https://systemd.io/BOOT_LOADER_SPECIFICATION/ defines a `devicetree-overlay` property.

**Comment by medude** [comment]
That's correct but a bit out-of-scope of this commit. We should add the support within a separate patch. Also sometimes someone don't wanna install the overlays because they are detected during runtime.

**Comment by medude** [comment]
Okay now it should be ready for merge :)

**Review by ejoerns — APPROVED** [review]

**Pull request merged**
